### ISSUE TITLE
Re-write Python binding using Cython

### ISSUE THREAD

**Issue by socketpair** [libyal/libqcow#10]
1. It's much faster to write
2. It's much simplier
3. Hand-writing Python bindings are much error-prone.
4. It's easy to add new functionality of C library, like writing, discarding and so on.
5. It's bi-lingual (Pytyhon2/Python3) automagically.

**Comment by joachimmetz** [comment]
Is this a question, a statement or a proposal?

* If this a question the answer is no, I don't have the time. 
* If this a statement, I'm not convinced. Unless you point me to a testing framework that can test Cython at C level
* If this a proposal, go ahead no one is holding you back.

**Comment by socketpair** [comment]
It's proposal. Seems, I will write Cython binding.

**Comment by socketpair** [comment]
Sorry, I will not write bindings since library is for reading images only, not writing.

**Comment by joachimmetz** [comment]
Then I'll close this issue. Thx for the suggestion.
