### ISSUE TITLE
Disallow exec to inherit file descriptors (O_CLOEXEC)

### ISSUE THREAD

**Issue by socketpair** [libyal/libqcow#11]

**Comment by joachimmetz** [comment]
Can you be more descriptive what is leaking where?

**Comment by socketpair** [comment]
If some program using you library calls `fork()` and then `execve()`, file descriptor connected to opened image will be accessible from some non-related process. for example, it can call `seek()`, and position will be changed also in original process.

It's true security-related problem.

**Comment by joachimmetz** [comment]
Why would the process be unrelated? Also the API nor ABI exposes file descriptor used by the library, so the forking process has to intentionally tamper with the file descriptor. 

> It's true security-related problem.

Why do you think this is a "true" security-related problem?

**Comment by socketpair** [comment]
Because completely unrelated process may read data or change seek position in opened qcow2 file.

It's not required to know file descriptor number. They are easily enumerated through /proc/self/fd.

For example, if program, using your library does `system("some-program")`, this `some-program` MAY read data or even affect main process (via calling `lseek()` and some other syscalls).

**Comment by socketpair** [comment]
For example, Python3 always sets O_CLOEXEC atomically (very important) in each function that creates new file descriptor.

Atomicityis important for multithreading programs which may call fork()+execve() in psearate thread between creating file descriptor and setting O_CLOEXEC on it.

**Comment by joachimmetz** [comment]
> For example, if program, using your library does system("some-program"), this some-program MAY read data or even affect main process (via calling lseek() and some other syscalls).

Thx for the explanation, your reference to "unrelated" is more clear now.

Thx, for the report I'll have a closer look. Seeing that the library intend to hides internals anyway, should not be problem to add O_CLOEXEC for platforms that support it.

**Comment by joachimmetz** [comment]
Moved this issue to libcfile (https://github.com/libyal/libcfile/issues/3) which handles the file access in libqcow.
