### ISSUE TITLE
Consider using preadv() / pwritev() 

### ISSUE THREAD

**Issue by socketpair** [libyal/libqcow#12]
1. I'ts faster (since only one syscall required)
2. it does not need locking for seek+operation. So you can eliminate seeking completely.

**Comment by joachimmetz** [comment]
How portable is this?

**Comment by socketpair** [comment]
```
Versions
preadv() and pwritev() first appeared in Linux 2.6.30; library support was added in glibc 2.10.

Conforming To
readv(), writev(): 4.4BSD (these system calls first appeared in 4.2BSD), POSIX.1-2001. Linux libc5 used size_t as the type of the iovcnt argument, and int as the return type.

preadv(), pwritev(): nonstandard, but present also on the modern BSDs.

Notes
```

**Comment by socketpair** [comment]
Anyway, I recommend you not to use any wrapper for IO. Just implement IO for each supported OS separately. Or, maybe for group of OSes.

For Windows it will be OverlappedIO, For non-Windows -- open()/read()/write() and optionally (if supported) preadv()/pwritev().

Just like SQLite/Python and so on.

**Comment by joachimmetz** [comment]
> Anyway, I recommend you not to use any wrapper for IO. Just implement IO for each supported OS separately. Or, maybe for group of OSes.

I cannot. The idea of abstracting the IO in libbfio is to allow reading QCOW images from other images, such as a RAW images of a disk containing qcow2 image.

I can have a look at using preadv() / pwritev() in libcfile.

**Comment by socketpair** [comment]
Also, I recommend you to examine `qemu-io` command. It has good abstration, allows to read/write not only qcow2, but many other formats (including network storages). It will be nice if you write library around qemu's `bdrv_*` functions.

**Comment by joachimmetz** [comment]
> It will be nice if you write library around qemu's bdrv_* functions.

How portable is this on platforms like Windows?

**Comment by socketpair** [comment]
VERY portable :) qemu works on Windows perfectly

**Comment by joachimmetz** [comment]
But it is currently embedded into qemu? or is this something that can be reused stand-alone?

**Comment by socketpair** [comment]
`qemu-io` is a stand-alone program. You can try it in you favourite Linux distro )or even Windows >:-)

Unfortunatelly, qemu-project does not provide any dynamic library  for block functionality.

**Comment by joachimmetz** [comment]
So qemu seems to be primarily GPLv2 which will conflict with using in LGPLv3 licensed code. This means that qemu code cannot be reused with libyal in the current state.

**Comment by joachimmetz** [comment]
Closing issue
