### ISSUE TITLE
Use fsync()/fdatasync() to prevent possible data corruption

### ISSUE THREAD

**Issue by socketpair** [libyal/libqcow#13]

**Comment by joachimmetz** [comment]
Can you be more descriptive what possible corruption, where?

If you want things to get addressed you'll have to be more descriptive and explain what and why you want things changed.

**Comment by joachimmetz** [comment]
Also how portable are fsync()/fdatasync()?

**Comment by socketpair** [comment]
Simple scenario:
1. write some data to qcow2 file. program complete.
2. powerfail.
3. power-on
4. image is corrupted.

The same may happen during internal qcow2 data manipulation. You should understand that any incomplete write (not acknowledged by fsync() or fadasync()) may corrupt image.

For example, qemu-img never corrupts image structure. And if write operations in it is complete, data is really permanent.

**Comment by socketpair** [comment]
fdatasync:

```
Conforming To
4.3BSD, POSIX.1-2001.
```

**Comment by socketpair** [comment]
Also, We need an option to inhibit fsyncing like qemu-img's `cache=unsafe`. And fdatasync only at image closing. (or even never)

**Comment by joachimmetz** [comment]
https://www.humboldt.co.uk/fsync-across-platforms/

> write some data to qcow2 file. program complete.

Libqcow does not write images at this point in time.

**Comment by socketpair** [comment]
Much better would be implementing of all caching modes of qemu - i.e. write-back, write-through, unsafe, none, directsync. Don't know if it is possible to work with qcow2 file in O_DIRECT mode, since it requires all IO to be page-aligned.

**Comment by socketpair** [comment]
O! sorry, I did not know that libqcow2 is read-only. Just started to do experiments (and read really works).

**Comment by joachimmetz** [comment]
Thx for the suggestion. I close this issue for now and revisit if/when write is added.
