### ISSUE TITLE
offset=${OFFSET}  - find some proper actual value if possible

### ISSUE THREAD

**Issue by dimyme** [libyal/libqcow#18]
`mount -o loop,ro,offset=${OFFSET} /mnt/fuse/qcow1 /mnt/file_system`

Where do I find the actual value of **OFFSET** ? taken from https://github.com/libyal/libqcow/wiki/Mounting

Maybe the **$** and the **{** and **}**  are a mistake and make the instruction FAIL  :-1: 

I tried all offsets given by 
`qcowinfo  -v  /home/YOU/.local/share/gnome-boxes/images/boxes-unknown`
and, of course, none was working!

Solution: quit libqcow, use [sth else](https://www.linuxunbound.com/2016/07/mounting-raw-and-qcow2-images/) instead.

**Comment by joachimmetz** [comment]
@dimyme do you expect someone to help you with an attitude like this?

**Comment by joachimmetz** [comment]
Marking as invalid since reporter mainly appears to want to rant
