### ISSUE TITLE
Request to indefinitely keep previous versions for pre-releases

### ISSUE THREAD

**Issue by VelocityRa** [libyal/libqcow#19]
The [vcpkg port](https://github.com/microsoft/vcpkg/blob/master/ports/libqcow/portfile.cmake#L3) of this uses specific releases. It breaks every time you make a new release and delete everything else, so perhaps you could keep old releases around?

**Comment by joachimmetz** [comment]
So first, I'm was aware of this vcpkg port or the release process behind, the maintainers never contacted/consulted me

Second these are pre-releases / under development, also see https://github.com/libyal/libyal/wiki, for which it is strongly recommended to keep up to date with the latest version.

Third vcpkg should be able to re-create a release based on the source, this is what `make dist` was made for.

Forth it sounds to me like a very fragile distribution process if it cannot account for newer version.

**Comment by VelocityRa** [comment]
Btw here's the initial vcpkg port / reasoning: https://github.com/microsoft/vcpkg/pull/17525

**Comment by VelocityRa** [comment]
Or preferably, CMake integration.

**Comment by joachimmetz** [comment]
> I'm not sure why you use Github "Releases" only for pre-releases and not actual releases?

Because I don't have the bandwidth to maintain releases at this point. This project is a single person best effort. People expect all kinds of additional commitments with final releases. 

> Or preferably, CMake integration.

why does every dist platform make its short comings the problem of the upstream project?

**Comment by VelocityRa** [comment]
It's not really a problem with libqcow. Just a feature request. To support the most widely used C/C++ build system.

**Comment by joachimmetz** [comment]
>  Just a feature request.

So you're agree-ing that you're making this a problem of the upstream, instead of e.g. Debian apt that keeps a copy of the source distribution package.

> To support the most widely used C/C++ build system.

According to who? based on what data?
