### ISSUE TITLE
Support for write operations?

### ISSUE THREAD

**Issue by IxaKylin** [libyal/libqcow#22]
I noticed that the related code for libqcow_file_write_buffer was removed in 2020. Did you encounter any difficulties in developing the write function?

**Comment by joachimmetz** [comment]
> I noticed that the related code for libqcow_file_write_buffer was removed in 2020. Did you encounter any difficulties in developing the write function?

for now read-only support is what I need and too busy with other priorities. If you want/need it, implement yourself or hire someone to do it for you.
