### ISSUE TITLE
understanding how to get 1K from 512 offset inside qcow3 image

### ISSUE THREAD

**Issue by vtolstov** [libyal/libqcow#3]
I have compressed qcow3 image file.

Can you helps me to understand how can i get 1K data from 512 byte offset inside the image (from vm point of view).

if that possible, please operate variable names like:

        Magick  uint32
        Version uint32

        BackingFileOffset uint64
        BackingFileSize   uint32

        ClusterBits           uint32
        Size                  uint64
        CryptMethod           uint32
        L1Size                uint32
        L1TableOffset         uint64
        RefcountTableOffset   uint64
        RefcountTableClusters uint32
        NbSnapshots           uint32
        SnapshotsOffset       uint64

        IncompatibleFeatures uint64
        CompatibleFeatures   uint64
        AutoclearFeatures    uint64
        RefcountOrder        uint32
        HeaderLength         uint32

**Comment by joachimmetz** [comment]
I opt reading https://github.com/libyal/libqcow/blob/master/documentation/QEMU%20Copy-On-Write%20file%20format.asciidoc

**Comment by vtolstov** [comment]
I'm try to understand this, but some words (i'm use find on page to understand how variable calculated) can't finded, so progress is slow =(

**Comment by joachimmetz** [comment]
> i'm use find on page to understand how variable calculated

Follow the references. Check the source.

> so progress is slow =(

Me trying to explain it to you will be even slower, largely due to limited time on my side.
