### ISSUE TITLE
Migrate to DokanY

### ISSUE THREAD

**Issue by Liryna** [libyal/libqcow#5]
Hi @joachimmetz,

That's a great project you have ! Mounting QCOW img would very interesting for peoples !

I seen that you have a compatibility with Dokan for Windows.
Dokan project has been abandonned by the maintainer so we forked to DokanY:
https://github.com/dokan-dev/dokany

We also have made a couple of changes that breaks compatibility with old dokan. If you plan to update your dokan wrapper here is our wiki:
https://github.com/dokan-dev/dokany/wiki/Update-dokan-legacy-application-to-Dokany

And also, feel free to ask if you need help !

**Comment by joachimmetz** [comment]
@Liryna thanks for the heads up. I indeed was planning to move away from legacy dokan and maybe move to dokanx. I'll have a look at dokany instead, when time permits.

**Comment by joachimmetz** [comment]
Seeing that DokanY only supports vs2015 and later, keeping Dokan legacy support around for now seeing it support vs2008 and later.

**Comment by joachimmetz** [comment]
* [x] Migrate to use stand alone dokan legacy (https://github.com/joachimmetz/dokan)
* [ ] Get AppVeyor tests running with dokan legacy and dokany (+/-)
* [ ] Implement dokany support and get it working (+/-)
* [ ] Deprecated dokan legacy support

**Comment by joachimmetz** [comment]
Got a basic implementation up and running. However is when idle dokany unmounts the file system with  "Ioctl failed for wait with code 995"

**Comment by joachimmetz** [comment]
TODO: get CI tests to pass.

**Comment by joachimmetz** [comment]
Code clean up and added last part of basic functionality https://github.com/libyal/libqcow/commit/3620501c28f0122b3d1253c6c19ace9693631c90. Closing issue since it is now complete.

**Comment by Liryna** [comment]
Hi @joachimmetz ,

Really appreciate updating to dokany ! When you feel that everything is ready for public release, ping me and will add the project to the dokan front page with others !

**Comment by joachimmetz** [comment]
@Liryna I assume you mean adding libqcow to the list below "Dokan is used in a variety of projects, a short list below." on http://dokan-dev.github.io/. You can mention it there if you want, seeing it has been using Dokan for a while now. 

Note that qcowmount is not a polished end-product but a CLI utility for a specific purpose. Seeing that Dokan was close to FUSE at the time, it was the easiest way to add Windows support.

FYI there are mount tools in other libyal projects (that also use Dokan) as well, namely libbde, libcreg, libewf, libewf-legacy, libfsapfs, libfvde, libhibr, libluksde, libmodi, libolecf, libphdi, libregf, libsmraw, libvhdi, libvmdk, libvshadow, libvslvm. I'll be gradually adding DokanY support to these as well.
