### ISSUE TITLE
Plans for adding support for backing file-based snapshots?

### ISSUE THREAD

**Issue by Rush** [libyal/libqcow#6]
I noticed that you list the feature as "unsupported". Do you plan to do it at one point or is it out of scope of this project?

**Comment by joachimmetz** [comment]
If time permits or an urgent need arises, yes I plan to add support of snapshots.

**Comment by i30817** [comment]
Backing store support + dosbox on compressed squashfs + rw overlayfs-fuse is what i'd use this for.

Currently dosbox can boot windows 95 (sorta) from raw image files. But placing those raw images on a ro mount + rw overlay means to copy the whole image file to the cache before using it when opened for writing (basically all images).... which would be quite painful indeed for 5 gb game installs.
Enter a backing qcow image support, suddenly only 'the saves and configs' need to be copyed, aka ≃ 1 mb. A nice dream but a few too many moving parts.
There is a qcow2 patch for dosbox but it is very naive and tries to copy the whole image into memory to support backing images. Completely unsuitable. If there was a quality library for it to use i think it'd do better.

**Comment by joachimmetz** [comment]
@i30817 the scope of this project is reading QCOW images for now. If snapshot support would be added it would be ro for the immediate future.

**Comment by joachimmetz** [comment]
Initial work on backing file support https://github.com/libyal/libqcow/commit/fa75d469b5dc152a7aa89200f1bea255013cd836
