### ISSUE TITLE
Does this not support write access?

### ISSUE THREAD

**Issue by genet022** [libyal/libqcow#7]
I see some ifdefs in the source that lead me to believe that this library does not support write access.

**Comment by joachimmetz** [comment]
There is no write support at the moment. Only read-only also per https://github.com/libyal/libqcow/blob/master/README

**Comment by genet022** [comment]
Thanks for the quick reply Joachim! Any timeline on when you plan to support writing?
Keep up the great work and fantastic support!

**Comment by i30817** [comment]
Backing store support + dosbox on compressed squashfs + rw overlayfs-fuse is what i'd use this for. 

Currently dosbox can boot windows 95 (sorta) from raw image files. But placing those raw images on a ro mount + rw overlay means to copy the whole image file to the cache before using it when opened for writing (basically all images).... which would be quite painful indeed for 5 gb game installs.
Enter a backing qcow image support, suddenly only 'the saves and configs' need to be copyed, aka ≃ 1 mb. A nice dream but a few too many moving parts. There is a qcow2 patch for dosbox but it very naive and tries to copy the whole image into memory to support backing images. Completely unsuitable. If there was a quality library for it to use i think it'd do better.

**Comment by pahome** [comment]
Sorry, I also have the same question about this.
Does the write to qcow files support now?

**Comment by joachimmetz** [comment]
> Any timeline on when you plan to support writing?

@genet022 Not soon, I'm extremely busy and write support has no priority for me.

Why not use the qemu-img tool instead?

> Does the write to qcow files support now?

@pahome nope
