### ISSUE TITLE
how to compress qcow2?

### ISSUE THREAD

**Issue by pahome** [libyal/libqcow#8]
Readme said that supported qcow2 features compression and encrytion.
But how to generate compression qcow2?
Is there any tutorial?

thx

**Comment by joachimmetz** [comment]
> But how to generate compression qcow2?

This project only reads qcow2 images. Generating them is out of scope. See qemu-img on how to generate compressed QCOW 2 images.

**Comment by pahome** [comment]
I mean is that ok to read compressed qcow2 image?

**Comment by joachimmetz** [comment]
yes, you read it the same as non-compressed images.
